baseURL = "http://guidopercu.dev/"
languageCode = "en-us"
title = "GuidoPercu.dev"
theme = "color"

[params]
  
  # Site description
  description = "I'm a Full Stack Engineer at Modus Create, where I create software projects using Python, PHP and AWS solutions. In my free time I enjoy reading books, learning about stock markets and practicing Karate."
  
  # Author
  author      = "Guido Percú"
  authorDesc  = "Guido Percú is a Full Stack Engineer at Modus Create, where he creates software projects using Python, PHP and AWS solutions. Born and raised in Brazil, he lives in Rio de Janeiro with his wife. When he is not coding, he enjoys reading books, learning about stock markets and practicing Karate."

  # Site cover, for Open Graph, Twitter Cards and Schema.org
  # It will be used if the current page doesn't have a image cover
  # File will be picked from the "assets" directory
  # Comment the lines if you don't want to use it
  #cover     = "img/cover.jpg"
  #coverAlt  = "A placeholder that doesn't deserve to be described."
  
  [params.style]
  
    # Dark mode as default
    # User preferences (site/system settings) will still have priority over it
    # The default is false
    isDark = true

    # Accent colors for light and dark mode respectively
    lightAccent  = "#225670" # Default is "#225670"
    darkAccent   = "#dd587c" # Default is "#dd587c"

    # More colors, pick as many as you want (not really sure if there's a limit)
    # Apparently these may not show up on every modern browser (ie. Firefox)
    # There's no default value. Used here just as example
    presets = [ "#6accd4", "#1f676b", "#f3a530"]

  # For a simple 404
  [params.notFound]
    title         = "Page not found"
    description   = "This page was not found."
    paragraph     = "Nothing to see here, buddy."

[languages]

  [languages.en]
  
    languageName = "English"

    [languages.en.menu]

      [[languages.en.menu.main]]
        name = "About"
        weight = 1
        url = "about/"

      [[languages.en.menu.main]]
        name = "Posts"
        weight = 2
        url = "posts/"
      
      [[languages.en.menu.main]]
        name = "Digital Garden"
        weight = 3
        url = "garden/"
      
      [[languages.en.menu.main]]
        name = "Library"
        weight = 4
        url = "library/"





